Porting run.sh  (obtained from 0.1.3-SNAPSHOT  )to window batch file run.bat. Testing environment settings are window 8.1 x64-based processor, JDK 1.6u45  and maven 3.2.1, netbeans 3.7.1 Testing Results: Just testing batch script to bring up server without adding , deleting, retrieving schema with three back-ends ( in-memory, file-system and zookeeper) , servers were bounced up correctly, except zookeeper 's gave warning messages, which could be caused by missing zookeeper in window testing machine since  CentOS6.4 linux ( missing installation of zookeeper ) had same warning messages
Below are warnings:

WARN  [org.apache.zookeeper.ClientCnxn         ] Session 0x0 for server null, unexpected error, closing socket
connection and attempting reconnect
java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.6.0_45]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:599) ~[na:1.6.0_45]
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[schema-repo-zk-bundle-0.
1.3-SNAPSHOT-withdeps.jar:0.1.3-SNAPSHOT]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[schema-repo-zk-bundle-0.1.3-SNAPSHOT-w
ithdeps.jar:0.1.3-SNAPSHOT]